from zExceptions import Unauthorized
if REQUEST is not None:
  raise Unauthorized

google_login = context

assert google_login.getPortalType() == "Google Login"
assert google_login.getValidationState() == "validated"

person = google_login.getParentValue()

if person.getDefaultEmailText() != google_login.getReference():
  raise ValueError('User email isnt same as as google login (%s, %s)' % (
    person.getDefaultEmailText(), google_login.getReference()
  ))

if dry_run:
  return

erp5_login = person.newContent(
  portal_type="ERP5 Login",
  reference=google_login.getReference(),
  # 128 is larger then the population, generated by the sample, so call 2x64
  password=person.Person_generatePassword(length=64)+person.Person_generatePassword(length=64)
)

erp5_login.checkConsistency()
erp5_login.validate()

google_login.invalidate()
